spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true
  #  mvc:
  #    static-path-pattern: /res/**

  web:
    resources:
      static-locations:
        [ classpath:/haha/]
      cache:
        period: 11000
      add-mappings: true
server:
  servlet:
#    context-path: /world

